// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi9VS9ChF31X6Ak4yzpfx_Pyx2iXvF4mA',
    appId: '1:357047358760:web:8bada17a2c48e555736c1d',
    messagingSenderId: '357047358760',
    projectId: 'organizzeapp-f8db3',
    authDomain: 'organizzeapp-f8db3.firebaseapp.com',
    storageBucket: 'organizzeapp-f8db3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8WjHHsxwWeY63VGdc0gdynbqbyKxST3Y',
    appId: '1:357047358760:android:83d960e584946341736c1d',
    messagingSenderId: '357047358760',
    projectId: 'organizzeapp-f8db3',
    storageBucket: 'organizzeapp-f8db3.appspot.com',
  );
}
